#!/bin/sh
set -e

# ==========================================================
# Alpine Linux 专属全能一键优化脚本
# ==========================================================

# 1. 颜色与基础变量
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
CYAN="\033[36m"
RESET="\033[0m"

LOG_FILE="/var/log/alpine_setup.log"
non_interactive=${NON_INTERACTIVE:-false}

# 适配 Alpine 的精简依赖包 (移除了 glibc 依赖项，换用 musl 兼容工具)
deps="curl wget git net-tools lsof tar unzip rsync pv sudo openbsd-netcat openssh-client jq openssl ca-certificates"

log() {
    echo -e "$1"
    echo -e "$1" | sed 's/\\033\[[0-9;]*m//g' >> "$LOG_FILE"
}

root_check() {
    if [ "$(id -u)" -ne 0 ]; then
        echo -e "${RED}❌ 请使用 root 用户运行此脚本${RESET}"
        exit 1
    fi
}

# 环境侦测：判断是独立虚拟机还是容器
detect_environment() {
    IS_CONTAINER=false
    if [ -f /.dockerenv ] || [ -f /run/.containerenv ] || grep -qaE "(container|docker|lxc)" /proc/1/environ /proc/1/cgroup 2>/dev/null; then
        IS_CONTAINER=true
        VIRT_TYPE="容器环境 (Docker/LXC)"
    else
        VIRT_TYPE="独立虚拟机/物理机 (KVM/XEN/VMware)"
    fi
    log "${blue}[INFO] 当前运行环境: ${VIRT_TYPE}${RESET}"
}

# 2. 系统更新与依赖安装
update_system() {
    log "\n${YELLOW}=============== 1. 系统更新与依赖 ===============${RESET}"
    log "${BLUE}正在更新 apk 软件源...${RESET}"
    apk update && apk upgrade
    
    log "${BLUE}正在安装基础依赖工具...${RESET}"
    for pkg in $deps; do
        if ! apk info -e "$pkg" >/dev/null 2>&1; then
            apk add "$pkg"
        fi
    done
    log "${GREEN}✅ 基础依赖安装完成${RESET}"
}

# 3. 设置主机名
configure_hostname() {
    log "\n${YELLOW}=============== 2. 主机名配置 ===============${RESET}"
    local new_hn="localhost"
    
    if [ "$IS_CONTAINER" = false ] && [ -f /etc/hostname ]; then
        echo "$new_hn" > /etc/hostname
        if command -v hostname >/dev/null 2>&1; then
            hostname "$new_hn"
        fi
    fi
    
    # 更新 /etc/hosts
    if grep -q "127.0.0.1" /etc/hosts; then
        sed -i "s/127.0.0.1.*/127.0.0.1\t$new_hn localhost/" /etc/hosts
    fi
    log "${GREEN}✅ 主机名配置完成${RESET}"
}

# 4. 语言与区域环境 (Locale)
configure_locale() {
    log "\n${YELLOW}=============== 3. 语言环境设置 ===============${RESET}"
    # Alpine 默认使用 musl-libc，通过安装 musl-locales 提供基础支持
    apk add musl-locales musl-locales-lang ttf-dejavu >/dev/null 2>&1
    
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    
    # 写入全局环境变量
    if [ -f /etc/profile ]; then
        grep -q "en_US.UTF-8" /etc/profile || echo -e "\nexport LANG=en_US.UTF-8\nexport LC_ALL=en_US.UTF-8" >> /etc/profile
    fi
    log "${GREEN}✅ 语言环境设为 en_US.UTF-8${RESET}"
}

# 5. 防火墙完全放行
configure_firewall() {
    log "\n${YELLOW}=============== 4. 防火墙完全放行 ===============${RESET}"
    
    # Alpine 常见防火墙为 awall 或 iptables
    if command -v iptables >/dev/null 2>&1; then
        log "${BLUE}[INFO] 正在清理 iptables 规则...${RESET}"
        iptables -F 2>/dev/null || true
        iptables -X 2>/dev/null || true
        iptables -P INPUT ACCEPT 2>/dev/null || true
        iptables -P FORWARD ACCEPT 2>/dev/null || true
        iptables -P OUTPUT ACCEPT 2>/dev/null || true
    fi
    
    if [ -d /etc/init.d ] && [ -f /etc/init.d/iptables ]; then
        rc-service iptables stop 2>/dev/null || true
        rc-update del iptables default 2>/dev/null || true
    fi
    log "${GREEN}✅ 防火墙限制已全面解除${RESET}"
}

# 6. BBR 与内核网络调优 (自动识别环境)
configure_bbr() {
    log "\n${YELLOW}=============== 5. BBR 与网络网络调优 ===============${RESET}"
    
    if [ "$IS_CONTAINER" = true ]; then
        log "${YELLOW}[SKIP] 当前为容器环境，共享宿主机内核，跳过内核参数修改。${RESET}"
        return 0
    fi
    
    log "${BLUE}正在配置优化级内核参数...${RESET}"
    local config_file="/etc/sysctl.d/99-bbr.conf"
    
    cat > "$config_file" << EOF
# 核心网络及 BBR 开启
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3

# 缓冲区深度适配
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# 队列与连接复用
net.core.somaxconn = 16384
net.ipv4.tcp_max_syn_backlog = 16384
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_slow_start_after_idle = 0
EOF
    sysctl -p "$config_file" >/dev/null 2>&1 || true
    log "${GREEN}✅ BBR 及网络队列调优成功${RESET}"
}

# 7. 传统 DNS 配置
configure_dns() {
    log "\n${YELLOW}=============== 6. DNS 配置 ===============${RESET}"
    log "${BLUE}正在修改 /etc/resolv.conf...${RESET}"
    
    # 解锁文件（防止被某些脚本锁死）
    chattr -i /etc/resolv.conf 2>/dev/null || true
    
    cat > /etc/resolv.conf << EOF
# Generated by Alpine Setup Script
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 2606:4700:4700::1111
EOF
    log "${GREEN}✅ DNS 优化完毕 (8.8.8.8 / 1.1.1.1)${RESET}"
}

# 8. Swap 虚拟内存配置 (1GB)
configure_swap() {
    log "\n${YELLOW}=============== 7. Swap 虚拟内存配置 ===============${RESET}"
    
    if [ "$IS_CONTAINER" = true ]; then
        log "${YELLOW}[SKIP] 容器环境无法独立挂载物理 Swap，跳过。${RESET}"
        return 0
    fi
    
    if swapon -s | grep -q 'partition\|file'; then
        log "${BLUE}系统已有可用 Swap，跳过创建${RESET}"
        return 0
    fi
    
    local free_space=$(df -m / | awk 'NR==2 {print $4}')
    if [ "$free_space" -lt 5120 ]; then
        log "${YELLOW}磁盘剩余空间小于 5GB，不建议创建 Swap，跳过。${RESET}"
        return 0
    fi
    
    log "${BLUE}正在使用 dd 创建 1GB Swap 镜像文件...${RESET}"
    dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    
    grep -q "/swapfile" /etc/fstab || echo "/swapfile none swap sw 0 0" >> /etc/fstab
    log "${GREEN}✅ 1GB 虚拟内存 Swap 配置完毕${RESET}"
}

# 9. SSH 端口与安全加固 (兼容 OpenRC / 纯容器模式)
configure_ssh() {
    log "\n${YELLOW}=============== 8. SSH 基础配置 ===============${RESET}"
    
    # 交互输入新端口
    if [ -z "$NEW_SSH_PORT" ] && [ "$non_interactive" = false ]; then
        echo -n "请输入新的 SSH 端口号 (直接回车跳过不变): "
        read -r NEW_SSH_PORT
    fi
    
    local ssh_conf="/etc/ssh/sshd_config"
    if [ -f "$ssh_conf" ] && [ -n "$NEW_SSH_PORT" ]; then
        sed -i "s/^#\?Port.*/Port $NEW_SSH_PORT/g" "$ssh_conf"
        log "${GREEN}✅ SSH 端口已设为: ${NEW_SSH_PORT}${RESET}"
        
        # 尝试重启服务（若存在 init 系统的独立 VM）
        if [ -f /etc/init.d/sshd ]; then
            rc-service sshd restart 2>/dev/null || true
        fi
    else
        log "${BLUE}SSH 端口未作变更${RESET}"
    fi
}

# 10. Fail2ban 安装与适配
configure_fail2ban() {
    log "\n${YELLOW}=============== 9. Fail2ban 暴破防护 ===============${RESET}"
    
    if [ "$IS_CONTAINER" = true ]; then
        log "${YELLOW}[SKIP] 容器环境由于缺少底层内核审计模块，跳过 Fail2ban 的安装。${RESET}"
        return 0
    fi
    
    log "${BLUE}正在安装 Fail2ban...${RESET}"
    apk add fail2ban >/dev/null
    
    cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
bantime = 86400
findtime = 300
maxretry = 5
ignoreip = 127.0.0.1/8

[sshd]
enabled = true
port = ${NEW_SSH_PORT:-22}
filter = sshd
logpath = /var/log/messages
EOF

    if [ -f /etc/init.d/fail2ban ]; then
        rc-update add fail2ban default 2>/dev/null || true
        rc-service fail2ban start 2>/dev/null || true
    fi
    log "${GREEN}✅ Fail2ban 暴破拦截配置完毕${RESET}"
}

# 11. 定时任务与网络追踪工具
install_tools() {
    log "\n${YELLOW}=============== 10. 实用工具集安装 ===============${RESET}"
    
    # Cronie 定时任务安装
    log "${BLUE}配置 cronie 计划任务服务...${RESET}"
    apk add cronie >/dev/null
    if [ -f /etc/init.d/crond ]; then
        rc-update add crond default 2>/dev/null || true
        rc-service crond start 2>/dev/null || true
    fi
    
    # 安装 NextTrace (底层依赖 libc 兼容包 gcompat)
    log "${BLUE}下载并配置路由追踪工具 NextTrace...${RESET}"
    apk add gcompat libc6-compat >/dev/null 2>&1 || true
    curl -sL https://nxtrace.org/nt | bash || true
    
    # 配置时区为上海
    log "${BLUE}修正系统时区为 Asia/Shanghai...${RESET}"
    apk add tzdata >/dev/null
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    echo "Asia/Shanghai" > /etc/timezone
    apk del tzdata >/dev/null
}

# 12. Docker 安装 (针对独立架构环境)
docker_install() {
    log "\n${CYAN}============ 11. Docker 容器引擎安装 ============${RESET}"
    
    if [ "$IS_CONTAINER" = true ]; then
        log "${YELLOW}[SKIP] 当前已是容器环境，无法进行嵌套 Docker 安装，跳过。${RESET}"
        return 0
    fi
    
    if [ "$non_interactive" = false ]; then
        echo -n "是否在当前 Alpine 主机上安装 Docker？[y/N]: "
        read -r INSTALL_DOCKER
        if [ "$INSTALL_DOCKER" != "y" ] && [ "$INSTALL_DOCKER" != "Y" ]; then
            log "${BLUE}已取消 Docker 安装${RESET}"
            return 0
        fi
    fi
    
    log "${BLUE}开始安装 Docker 引擎与 Docker-Compose...${RESET}"
    apk add docker docker-cli-compose >/dev/null
    
    if [ -f /etc/init.d/docker ]; then
        rc-update add docker default >/dev/null 2>&1
        rc-service docker start >/dev/null 2>&1
    fi
    log "${GREEN}✅ Docker 环境配置成功${RESET}"
}

# 13. 系统垃圾清理
clean_system() {
    log "\n${YELLOW}=============== 12. 极简系统瘦身清理 ============${RESET}"
    log "${BLUE}正在深度剔除 Alpine 缓存包...${RESET}"
    rm -rf /var/cache/apk/*
    rm -rf /tmp/* /var/tmp/*
    log "${GREEN}✅ 清理工作已顺利完成${RESET}"
}

# 主流程控制
main() {
    clear
    echo -e "${CYAN}======================================================${RESET}"
    echo -e "${GREEN}            Alpine Linux 专属全能优化                 ${RESET}"
    echo -e "${CYAN}======================================================${RESET}"
    
    root_check
    detect_environment
    
    if [ "$non_interactive" = false ]; then
        echo -n "是否立刻开始执行一键优化？ [Y/n]: "
        read -r CONFIRM
        if [ "$CONFIRM" = "n" ] || [ "$CONFIRM" = "N" ]; then
            echo -e "${BLUE}已主动退出。${RESET}"
            exit 0
        fi
    fi
    
    update_system
    configure_hostname
    configure_locale
    configure_firewall
    configure_bbr
    configure_dns
    configure_swap
    configure_ssh
    configure_fail2ban
    install_tools
    docker_install
    clean_system
    
    log "${GREEN}✨ 针对 Alpine Linux 的所有优化项目已全部处理完毕！${RESET}"
    
    # 容器环境不执行 reboot 退出，独立 VM 询问或直接执行
    if [ "$IS_CONTAINER" = true ]; then
        log "${YELLOW}容器环境无需重启，优化立即生效。${RESET}"
    else
        log "${YELLOW}系统将在 3 秒后安全重启以使内核及服务生效...${RESET}"
        sleep 3
        reboot
    fi
}

main "$@"
